# NumPy UltraQuick Tutorial

Import the required modules:

In [1]:
import numpy as np

Create the following output:
label = (3)(feature) + 4, where the first value == 22

In [2]:
feature = np.arange(6,21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
label = (feature * 3) + 4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


Now add noise to the array, using random floating-point values from +2 to -2:

In [4]:
noise = (np.random.random([15]) * 4) -2
print(noise)

[-0.1879959   1.88635779  1.33769788  0.72856236  1.28290658  0.99354457
 -0.36337295  1.8072958   0.09741241  0.90032872  0.38619369  1.89678912
  0.48487557 -1.71621817  1.65030103]


In [5]:
label = noise * label
print(label)

[  -4.1359099    47.15894469   37.45554062   22.5854331    43.61882377
   36.76114913  -14.53491805   77.71371959    4.48097106   44.11610723
   20.08207211  104.32340152   28.12278298 -104.68930845  105.61926605]


create a numpy random multidimensional array:

In [6]:
ar = np.random.randint(low=1, high=100, size=(4,4))
print(ar)

[[38 42 81 83]
 [14 42 11 84]
 [81 97 35 14]
 [14 78  3 62]]
