# Pandas UltraQuick Tutorial

Import required libraries:

In [1]:
import numpy as np
import pandas as pd

Create a 3x4 DataFrame with columns Eleanor, Chidi, Tahani, & Jason. Populate with randint from 0-100.

In [4]:
a34 = np.random.randint(low=0, high=101, size=(3,4))
print(a34)

[[15 40 55 91]
 [92 89 78  1]
 [79 66  4 12]]


In [9]:
colnm = ['Eleanor', 'Chidi', 'Tahani', 'Jason']
df1 = pd.DataFrame(data=a34, columns=colnm)
print(df1)
print("\nSecond row of Eleanor: %d\n" % df1['Eleanor'][1])

   Eleanor  Chidi  Tahani  Jason
0       15     40      55     91
1       92     89      78      1
2       79     66       4     12

Second row of Eleanor: 92



Create a fifth column "Janet", with value = row sums of Tahani + Jason

In [12]:
df1['Janet'] = df1['Jason'] + df1['Tahani']
print(df1)

   Eleanor  Chidi  Tahani  Jason  Janet
0       15     40      55     91    146
1       92     89      78      1     79
2       79     66       4     12     16


Create a true copy, and a simple reference of the previous DataFrame:

In [ ]:
df_ref = df1
df_cpy = df1.copy()
